apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: webapp-rs
spec:
 selector:
  matchLabels:
   appname: webapp61
 replicas: 5
 template:
  metadata:
   labels:
    appname: webapp61
  spec:
   containers:
   - name: webapp
     image: barisv/nodewebapp1:3