apiVersion: v1
kind: Service
metadata:
 name: webapp-service
spec:
 # this defines which pods are going to be represented by this service
 # the service becomes network enpoint for either other services
 # or maybe external users to connect to (eg browser)
 selector:
  appname: webapp61
 ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30083

 type: NodePort
